openapi: 3.0.0
info:
  version: '1.0'
  title: Product API
  description: Demo OpenAPI for Product
  termsOfService: 'https://google.com/'
  contact:
    name: TechFolks
    url: 'https://demo.google.com'
    email: demo@demo.com
  license:
    name: TechFolks License
    url: 'https://demo.com'
tag:
  - name: Product
paths:
  /products:
    get:
      description: Obtain information of all product in database
      tags:
        - Product
      parameters:
        - name: bodylimit
          in: query
          description: the amount of product returned.
          schema:
            type: integer
            minimum: 10
            maximum: 20
            example: 15
        - name: pagelimit
          in: query
          description: the paged to return emplyee info.
          schema:
            type: integer
            minimum: 1
            maximum: 5
            example: 2
      responses:
        '200':
          description: Successful pull of Product info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      description: Creates a new product in the database
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Successfully created an employee
  /products/{id}:
    get:
      description: Obtain information about specific product
      tags:
        - Product
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the product
          schema:
            type: integer
            example: 54
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      description: This is the Product model
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          description: Product name
          type: string
          example: Aveeno Moisturizer
        price:
          type: string
          description: Product price
          example: $20
